Name = Arav Mahind

Branch-Div = CMPN-A

Roll = 24102A2008

Subject = R Programming

Week = 7

Sequences

In [ ]:
seq(from=1, to=10, length.out=1)

[1] 1

In [ ]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
seq(-1:-10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [ ]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x = 2
seq(1, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [ ]:
x = seq(1, 50, 1/2)

In [ ]:
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [ ]:
y = 2*x

In [ ]:
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

Sequences: Index vector

In [ ]:
x = c(9, 8, 7, 6)

In [ ]:
ind = seq(along=x)
ind

[1] 1 2 3 4

In [ ]:
x[ind[2]]

[1] 8

In [ ]:
x[2]

[1] 8

Generating current time and date

In [ ]:
Sys.time()

[1] "2026-09-03 04:19:51 UTC"

In [ ]:
Sys.Date()

[1] "2026-09-03"

Generating  sequences of dates

In [ ]:
seq(as.Date("2010-01-01"), as.Date("2024-01-01"), by="years")

 [1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
 [6] "2015-01-01" "2016-01-01" "2017-01-01" "2018-01-01" "2019-01-01"
[11] "2020-01-01" "2021-01-01" "2022-01-01" "2023-01-01" "2024-01-01"

In [ ]:
seq(as.Date("2010-01-01"), by="years", length=15)

 [1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
 [6] "2015-01-01" "2016-01-01" "2017-01-01" "2018-01-01" "2019-01-01"
[11] "2020-01-01" "2021-01-01" "2022-01-01" "2023-01-01" "2024-01-01"

In [ ]:
seq(as.Date("2010-01-01"), by="days", length=6)

[1] "2010-01-01" "2010-01-02" "2010-01-03" "2010-01-04" "2010-01-05"
[6] "2010-01-06"

In [ ]:
seq(as.Date("2010-01-01"), by="months", length=6)

[1] "2010-01-01" "2010-02-01" "2010-03-01" "2010-04-01" "2010-05-01"
[6] "2010-06-01"

To find sequence with defining start and end dates

In [ ]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")

In [ ]:
out = seq(enddate, startdate, by="-1 month")

In [ ]:
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

Generating sequences of  alphabets

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
letters[1:2]

[1] "a" "b"

In [ ]:
typeof(letters)

[1] "character"

In [ ]:
letters[34]

[1] NA

In [ ]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
LETTERS[10]

[1] "J"

Repeats

In [ ]:
x = c(1, 2, 3, 4, 5)

In [ ]:
rep(x)

[1] 1 2 3 4 5

In [ ]:
rep(x, times=3)

 [1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [ ]:
rep(x, each=3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5

Every object is repeated  a different number of times:

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(x, 3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [ ]:
rep(x, 3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

Repetition of characters

In [ ]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [ ]:
rep(2, length=5)

[1] 2 2 2 2 2

In [ ]:
rep(c(2, 3), length=5)

[1] 2 3 2 3 2

In [ ]:
rep(x, length=5)

[1] 1 3 2 4 1

Sorting, Ordering and Mode

Sorting

In [ ]:
sort(x)

[1] 1 2 3 4

In [ ]:
sort(x, decreasing=TRUE)

[1] 4 3 2 1

Ordering

In [ ]:
x = c(1, 5, 2, 3)

In [ ]:
order(x)

[1] 1 3 4 2

In [ ]:
order(x, decreasing=T)

[1] 2 4 3 1

Mode

In [ ]:
mode(2)

[1] "numeric"

In [ ]:
mode(x)

[1] "numeric"

In [ ]:
mode("India")

[1] "character"

In [ ]:
mode(factor(c("MP", "UP")))

[1] "numeric"

In [ ]:
mode(list("India", "USA"))

[1] "list"

In [ ]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [ ]:
mode(print)

[1] "function"

Lists

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [ ]:
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
x1[2, 1]

[1] 3

In [ ]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [ ]:
matlist = list(x1, x2)

In [ ]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [ ]:
matlist[[1]][1, 2]

[1] 2

In [ ]:
z1 = list(c("water", "juice", "lemonade"), rep(1:4, each=2), matrix(data=5:8, nrow=2, ncol=2, byrow=T))

In [ ]:
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [ ]:
z1[[1]][1]

[1] "water"